config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#homepage'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :topic, presence: true, length: {minimum: 4, maximum: 15}
  validates :description, presence: true, length: {minimum: 10, maximum: 50}
  validates :city, presence: true, length: {minimum: 2, maximum: 18}
  validates :country, presence: true, length: {minimum: 3, maximum: 20}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  before_save {self.email = email.downcase}
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum:3, maximum:25}
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {maximum: 105}, format: {with: VALID_EMAIL_REGEX}
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  def new
    @article = Article.new

  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
   if  @article.save
     flash[:success] = "article successfully created"
    redirect_to article_path(@article)
   else
     render 'new'
   end
  end

  def show
    @article = Article.find(params[:id])
  end
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:danger] = "Article Deleted successfully!"
    redirect_to articles_path
  end
  def edit

    @article = Article.find(params[:id])
  end
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = "Article updated successfully"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end



  private
  def article_params
    params.require(:article).permit(:topic, :description, :city, :country)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def homepage

  end

  def about

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def index
@users = User.paginate(page: params[:page], per_page: 5)
end
  def new
  @user = User.new
end
  def create
  @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome #{@user.username}"
      redirect_to articles_path()
      else
      render 'new'
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Article updated successfully"
      redirect_to articles_path
      else
      render 'edit'
    end
  end
  def show
  @user = User.find(params[:id])
  @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end
  private
  def user_params
  params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size: 80})
  gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/articles/_article.html.erb
  <% obj.each do |article| %>
<div class = "row">
  <div class = "col-xs-8 col-xs-offset-2">
    <div class = "well well-lg">
      <div class = "article-title">
        <%= link_to article.topic, article_path(article) %>
      </div>
    <div class = "article-description">
      <%= truncate(article.description, length: 100) %>
      <div class = "timing"><small> Created by: <%= article.user.username if article.user %> <%= time_ago_in_words(article.created_at) %> ago,
        Updated at: <%= article.updated_at %> ago.</small></div>
      </div>
    <div class = "article-city">
      <%= article.city %>
      </div>
   <div class = "article-country">
      <%= article.country %>
    </div>
    <div class = "articles-action">

  <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-xs btn-primary' %>
  <%= link_to 'Delete', article_path(article), method: :delete, data: {confrim: "Are you sure, this can't be undone"},
                                               class: 'btn btn-xs btn-danger' %>

  </div>
    </div>
  </div>
</div>


  <% end %>

app/views/articles/edit.html.erb
<h1>Edit your article</h1>

<%= render 'shared/errors', obj: @article %>

<div class = 'row'>
  <div class = 'col-xs-12'>
      <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class = "form-group">
        <div class = "control-label col-sm-2">
        <%= f.label :topic %>
        </div>
        <div class = "col-sm-8">
        <%= f.text_field :topic, class: "form-control",  autofocus: true %>
        </div>
    </div>

     <div class = "form-group">
       <div class = "control-label col-sm-2">

        <%= f.label :description %>
       </div>
       <div class = "col-sm-7">
        <%= f.text_area :description, rows: 10, class: "form-control", autofocus: true %>
       </div>
    </div>
       <div class = "form-group">
        <div class = "control-label col-sm-2">
        <%= f.label :city %>
        </div>
        <div class = "col-sm-4">
        <%= f.text_area :city,rows: 1, class: "form-control"  %>
        </div>
       </div>

      <div class = "form-group">
        <div class = "control-label col-sm-2">
        <%= f.label :country %>
        </div>
        <div class = "col-sm-4">
        <%= f.text_area :country, rows: 1, class: "form-control" %>
        </div>
       </div>


      <div class = "form-group">
        <div class = "col-sm-offset-2 col-sm-2">
        <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
       </div>


      <% end %>
      <%= link_to 'Cancel', articles_path %>
  </div>
</div>

app/views/articles/index.html.erb
<h1 align = "center">The  listed articles are</h1>
<div align = "center">
  <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align = "center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create a new Article</h1>
<%= render 'shared/errors', obj: @article %>
<div class = 'row'>
  <div class = 'col-xs-12'>
      <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class = "form-group">
        <div class = "control-label col-sm-2">
        <%= f.label :topic %>
        </div>
        <div class = "col-sm-8">
        <%= f.text_field :topic, class: "form-control",  autofocus: true %>
        </div>
    </div>

     <div class = "form-group">
       <div class = "control-label col-sm-2">

        <%= f.label :description %>
       </div>
       <div class = "col-sm-7">
        <%= f.text_area :description, rows: 10, class: "form-control", autofocus: true %>
       </div>
    </div>
       <div class = "form-group">
        <div class = "control-label col-sm-2">
        <%= f.label :city %>
        </div>
        <div class = "col-sm-4">
        <%= f.text_area :city,rows: 1, class: "form-control"  %>
        </div>
       </div>

      <div class = "form-group">
        <div class = "control-label col-sm-2">
        <%= f.label :country %>
        </div>
        <div class = "col-sm-4">
        <%= f.text_area :country, rows: 1, class: "form-control" %>
        </div>
       </div>


      <div class = "form-group">
        <div class = "col-sm-offset-2 col-sm-2">
        <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
       </div>


      <% end %>
      <%= link_to 'Cancel', articles_path %>
  </div>
</div>

app/views/articles/show.html.erb
<h2 align = "center">Title: <%= @article.topic %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
  <ul class = "listing">
    <div class = "row">
      <div class = "col-md-4 col-md-offset-4">
        <li align = "center"><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
        <li class = "article-title center">
          <%= link_to @article.user.username, user_path(@article.user) %> </li>
        <li class = "center"><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
      </div>
    </div>
  </ul>
  <% end %>
  <h4 align = "center" class ="description" ><strong>Description:</strong></h4>
 <hr>
  <%= simple_format(@article.description) %>
  <hr>
   <h5><strong>City: <%= @article.city %></strong></h5>
  <h5><strong>Country: <%= @article.country %></strong></h5>

  <div class = "articles-action">

  <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-xs btn-primary' %>
  <%= link_to 'Delete', articles_path(@article), method: :delete, data: {confrim: "Are you sure, this can't be undone"},
                                               class: 'btn btn-xs btn-danger' %>
  <%= link_to 'View articles', articles_path, class: 'btn btn-xs btn-primary' %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class = "container">
  <footer class = "footer">
    <small>
      Copyright &copy;Created by <a href = "https://www.facebook.com">Divesh Chadha </a>and <a href = "https://www.facebook.com">Nivin Mathews</a>
    </small>
    <nav>
      <ul>

        <li><%= link_to "About", about_path %></li>

      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class = "rows">
  <div class = "col-xs-10 col-xs-offset-1">
  <% flash.each do |name, msg| %>
    <div class = 'alert alert-<%= "#{name}" %>'>
      <a href="#" class = "close" data-dismiss="alert">&#215; </a>
<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "canvas", root_path, class:"navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li ><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><%= link_to "Articles", articles_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Article", new_article_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>First</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>

<div class = "container">
<%= yield %>
  </div>
  <%= debug(params) if Rails.env.development? %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<h1>contact info</h1>
<b>1234567890</b>

<%= link_to 'home', root_path %>

app/views/pages/homepage.html.erb
<div class= "center jumbotron">

  <h1>canvas</h1>


<%= link_to "Sign up", "#", class: "btn btn-primary btn-large btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class = "row">
  <div class = "col-xs-8 col-xs-offset-2">
    <div class = "panel panel-danger">
      <div class = "panel-heading">
                     <h2 class = "panel-title">
                       <%= pluralize(obj.errors.count, "error") %>
                       prohibited this article from being saved:
        </h2>
        <div class = "panel-body">
          <ul>
          <%  obj.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/users/edit.html.erb
<h1 align="center">Edit Your Profile</h1>
<%= render 'shared/errors', obj: @user %>
<div class = 'row'>
  <div class = 'col-xs-12'>
      <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class = "form-group">
        <div class = "control-label col-sm-2">
        <%= f.label :Username %>
        </div>
        <div class = "col-sm-8">
        <%= f.text_field :username, class: "form-control",  autofocus: true %>
        </div>
    </div>

     <div class = "form-group">
       <div class = "control-label col-sm-2">

        <%= f.label :email %>
       </div>
       <div class = "col-sm-7">
        <%= f.email_field :email, rows: 1, class: "form-control", autofocus: true %>
       </div>
    </div>
    <div class = "form-group">
       <div class = "control-label col-sm-2">

        <%= f.label :Password %>
       </div>
       <div class = "col-sm-7">
        <%= f.password_field :password, rows: 1, class: "form-control", autofocus: true %>
       </div>
    </div>






      <div class = "form-group">
        <div class = "col-sm-offset-2 col-sm-2">
        <%= f.submit  "edit", class: 'btn btn-primary btn-lg' %>
        </div>
       </div>


      <% end %>
      <%= link_to 'Cancel', articles_path %>
  </div>
</div>

app/views/users/index.html.erb
<h1 align = "center">gamers</h1>
<div align = "center">
  <%= will_paginate %>
<% @users.each do |user| %>
  <ul class = "listing">
    <div class = "row">
      <div class = "col-md-4 col-md-offset-4">
        <li><%= link_to gravatar_for(user), user_path(user) %></li>
        <li class = "article-title">
          <%= link_to user.username, user_path(user) %> </li>
        <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
      </div>
    </div>
  </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign Up</h1>
<%= render 'shared/errors', obj: @user %>
<div class = 'row'>
  <div class = 'col-xs-12'>
      <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class = "form-group">
        <div class = "control-label col-sm-2">
        <%= f.label :Username %>
        </div>
        <div class = "col-sm-8">
        <%= f.text_field :username, class: "form-control",  autofocus: true %>
        </div>
    </div>

     <div class = "form-group">
       <div class = "control-label col-sm-2">

        <%= f.label :email %>
       </div>
       <div class = "col-sm-7">
        <%= f.email_field :email, rows: 1, class: "form-control", autofocus: true %>
       </div>
    </div>
    <div class = "form-group">
       <div class = "control-label col-sm-2">

        <%= f.label :Password %>
       </div>
       <div class = "col-sm-7">
        <%= f.password_field :password, rows: 1, class: "form-control", autofocus: true %>
       </div>
    </div>






      <div class = "form-group">
        <div class = "col-sm-offset-2 col-sm-2">
        <%= f.submit  "Sign Up", class: 'btn btn-primary btn-lg' %>
        </div>
       </div>


      <% end %>
      <%= link_to 'Cancel', articles_path %>
  </div>
</div>

app/views/users/show.html.erb
<h1 allign = "center">Welcome to <%= @user.username %>'s page </h1>
<div class = "row">
  <div class = "col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<h4 allign = "center">Welcome to <%= @user.username %>'s Articles </h4>
<div class = "center">
  <%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div class = "center">
  <%= will_paginate @user_articles %>
</div>